"""add medications table

Revision ID: 294d2581f5c7
Revises: 70fc9088ecc2
Create Date: 2026-07-05 21:04:58.363694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '294d2581f5c7'
down_revision: Union[str, Sequence[str], None] = '70fc9088ecc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_profile_id', sa.Integer(), nullable=True),
    sa.Column('drug_name', sa.String(length=255), nullable=False),
    sa.Column('atc_code', sa.String(length=20), nullable=True),
    sa.Column('dose_value', sa.Float(), nullable=True),
    sa.Column('dose_unit', sa.String(length=50), nullable=True),
    sa.Column('dosage_text', sa.String(length=500), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name='ck_medications_end_after_start'),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_atc_code'), 'medications', ['atc_code'], unique=False)
    op.create_index(op.f('ix_medications_drug_name'), 'medications', ['drug_name'], unique=False)
    op.create_index('ix_medications_patient_drug_start', 'medications', ['patient_profile_id', 'drug_name', 'start_date'], unique=False)
    op.create_index(op.f('ix_medications_patient_profile_id'), 'medications', ['patient_profile_id'], unique=False)
    op.create_index(op.f('ix_medications_start_date'), 'medications', ['start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medications_start_date'), table_name='medications')
    op.drop_index(op.f('ix_medications_patient_profile_id'), table_name='medications')
    op.drop_index('ix_medications_patient_drug_start', table_name='medications')
    op.drop_index(op.f('ix_medications_drug_name'), table_name='medications')
    op.drop_index(op.f('ix_medications_atc_code'), table_name='medications')
    op.drop_table('medications')
    # ### end Alembic commands ###
