"""add drug_interactions table

Revision ID: 4866a7e4c6ea
Revises: 294d2581f5c7
Create Date: 2026-07-06 21:01:08.557851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4866a7e4c6ea'
down_revision: Union[str, Sequence[str], None] = '294d2581f5c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drug_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('side_a', sa.JSON(), nullable=False),
    sa.Column('side_b', sa.JSON(), nullable=False),
    sa.Column('severity', sa.Enum('CONTRAINDICATED', name='interaction_severity'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('knowledge_source_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drug_interactions_knowledge_source_id'), 'drug_interactions', ['knowledge_source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drug_interactions_knowledge_source_id'), table_name='drug_interactions')
    op.drop_table('drug_interactions')
    # ### end Alembic commands ###
