"""refactor persistence layer

Revision ID: 4bda576df67c
Revises: 04ca1b3f0429
Create Date: 2026-07-01 17:20:44.785860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bda576df67c'
down_revision: Union[str, Sequence[str], None] = '04ca1b3f0429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_logs_id'), table_name='system_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_system_logs_id'), 'system_logs', ['id'], unique=False)
    # ### end Alembic commands ###
