"""add imaging_studies table

Revision ID: 70fc9088ecc2
Revises: 1dde201b18a4
Create Date: 2026-07-05 14:50:43.075354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70fc9088ecc2'
down_revision: Union[str, Sequence[str], None] = '1dde201b18a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imaging_studies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_profile_id', sa.Integer(), nullable=True),
    sa.Column('study_type', sa.Enum('xray', 'ct', 'mri', 'ultrasound', 'mammography', 'other', name='imaging_study_type'), nullable=False),
    sa.Column('body_part', sa.String(length=255), nullable=False),
    sa.Column('study_date', sa.Date(), nullable=False),
    sa.Column('facility_name', sa.String(length=255), nullable=True),
    sa.Column('radiologist_conclusion', sa.Text(), nullable=True),
    sa.Column('image_file_path', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imaging_studies_patient_profile_id'), 'imaging_studies', ['patient_profile_id'], unique=False)
    op.create_index('ix_imaging_studies_patient_type_date', 'imaging_studies', ['patient_profile_id', 'study_type', 'study_date'], unique=False)
    op.create_index(op.f('ix_imaging_studies_study_date'), 'imaging_studies', ['study_date'], unique=False)
    op.create_index(op.f('ix_imaging_studies_study_type'), 'imaging_studies', ['study_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_imaging_studies_study_type'), table_name='imaging_studies')
    op.drop_index(op.f('ix_imaging_studies_study_date'), table_name='imaging_studies')
    op.drop_index('ix_imaging_studies_patient_type_date', table_name='imaging_studies')
    op.drop_index(op.f('ix_imaging_studies_patient_profile_id'), table_name='imaging_studies')
    op.drop_table('imaging_studies')
    # ### end Alembic commands ###
