"""create system logs table

Revision ID: de66a32d894e
Revises: 
Create Date: 2026-07-01 17:03:42.879085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = 'de66a32d894e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


LEGACY_TABLES = [
    'health_records',
    'health_documents',
    'profile_anthropometry',
    'profile_thyroid_oncology',
    'family_members',
    'profile_personal',
    'profile_medical_history',
    'health_events',
    'lab_results',
    'persons',
    'profiles',
    'medical_documents',
    'observations',
]


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_logs_id'), 'system_logs', ['id'], unique=False)

    # Legacy cleanup: ці таблиці існують лише на базах даних, що
    # передують модульній архітектурі FHOS (ручна SQLite-схема до
    # Alembic). На будь-якій новій базі (PostgreSQL, чи нова SQLite)
    # цих таблиць немає і не буде — тому кожне видалення захищене
    # перевіркою існування. Без цього PostgreSQL Compatibility Checklist
    # виявив: цей крок ламається на першій же міграції з нуля.
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = set(inspector.get_table_names())

    for table_name in LEGACY_TABLES:
        if table_name not in existing_tables:
            continue

        index_name = f'ix_{table_name}_id'
        existing_indexes = {idx['name'] for idx in inspector.get_indexes(table_name)}
        if index_name in existing_indexes:
            op.drop_index(index_name, table_name=table_name)

        op.drop_table(table_name)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('health_record_id', sa.INTEGER(), nullable=True),
    sa.Column('observation_date', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('value_text', sa.VARCHAR(), nullable=True),
    sa.Column('value_number', sa.FLOAT(), nullable=True),
    sa.Column('unit', sa.VARCHAR(), nullable=True),
    sa.Column('source', sa.VARCHAR(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['health_record_id'], ['health_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observations_id'), 'observations', ['id'], unique=False)
    op.create_table('medical_documents',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('document_type', sa.VARCHAR(), nullable=True),
    sa.Column('source', sa.VARCHAR(), nullable=True),
    sa.Column('file_path', sa.VARCHAR(), nullable=True),
    sa.Column('document_date', sa.DATE(), nullable=True),
    sa.Column('confidence_score', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['family_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_documents_id'), 'medical_documents', ['id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('surname', sa.VARCHAR(), nullable=True),
    sa.Column('first_name', sa.VARCHAR(), nullable=True),
    sa.Column('middle_name', sa.VARCHAR(), nullable=True),
    sa.Column('birth_date', sa.VARCHAR(), nullable=True),
    sa.Column('sex', sa.VARCHAR(), nullable=True),
    sa.Column('height_cm', sa.FLOAT(), nullable=True),
    sa.Column('weight_kg', sa.FLOAT(), nullable=True),
    sa.Column('blood_group', sa.VARCHAR(), nullable=True),
    sa.Column('rhesus', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.create_table('persons',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('surname', sa.VARCHAR(), nullable=True),
    sa.Column('first_name', sa.VARCHAR(), nullable=True),
    sa.Column('middle_name', sa.VARCHAR(), nullable=True),
    sa.Column('birth_date', sa.VARCHAR(), nullable=True),
    sa.Column('sex', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persons_id'), 'persons', ['id'], unique=False)
    op.create_table('lab_results',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.Column('test_name_uk', sa.VARCHAR(), nullable=False),
    sa.Column('test_name_original', sa.VARCHAR(), nullable=True),
    sa.Column('value', sa.FLOAT(), nullable=True),
    sa.Column('unit', sa.VARCHAR(), nullable=True),
    sa.Column('reference_range', sa.VARCHAR(), nullable=True),
    sa.Column('lab_name', sa.VARCHAR(), nullable=True),
    sa.Column('result_date', sa.DATE(), nullable=True),
    sa.Column('source_document_id', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['family_members.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['medical_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_results_id'), 'lab_results', ['id'], unique=False)
    op.create_table('health_events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('health_record_id', sa.INTEGER(), nullable=True),
    sa.Column('event_date', sa.VARCHAR(), nullable=True),
    sa.Column('event_type', sa.VARCHAR(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('medical_domain', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['health_record_id'], ['health_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_events_id'), 'health_events', ['id'], unique=False)
    op.create_table('profile_medical_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('profile_id', sa.INTEGER(), nullable=True),
    sa.Column('disability_status', sa.VARCHAR(), nullable=True),
    sa.Column('chronic_diseases', sa.TEXT(), nullable=True),
    sa.Column('surgeries', sa.TEXT(), nullable=True),
    sa.Column('allergies', sa.TEXT(), nullable=True),
    sa.Column('oncology_history', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id')
    )
    op.create_index(op.f('ix_profile_medical_history_id'), 'profile_medical_history', ['id'], unique=False)
    op.create_table('profile_personal',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('profile_id', sa.INTEGER(), nullable=True),
    sa.Column('surname', sa.VARCHAR(), nullable=True),
    sa.Column('first_name', sa.VARCHAR(), nullable=True),
    sa.Column('middle_name', sa.VARCHAR(), nullable=True),
    sa.Column('birth_date', sa.VARCHAR(), nullable=True),
    sa.Column('sex', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id')
    )
    op.create_index(op.f('ix_profile_personal_id'), 'profile_personal', ['id'], unique=False)
    op.create_table('family_members',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(), nullable=False),
    sa.Column('birth_date', sa.DATE(), nullable=True),
    sa.Column('sex', sa.VARCHAR(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_members_id'), 'family_members', ['id'], unique=False)
    op.create_table('profile_thyroid_oncology',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('profile_id', sa.INTEGER(), nullable=True),
    sa.Column('total_thyroidectomy', sa.BOOLEAN(), nullable=True),
    sa.Column('thyroidectomy_year', sa.INTEGER(), nullable=True),
    sa.Column('thyroid_cancer_history', sa.BOOLEAN(), nullable=True),
    sa.Column('levothyroxine_therapy', sa.BOOLEAN(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id')
    )
    op.create_index(op.f('ix_profile_thyroid_oncology_id'), 'profile_thyroid_oncology', ['id'], unique=False)
    op.create_table('profile_anthropometry',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('profile_id', sa.INTEGER(), nullable=True),
    sa.Column('height_cm', sa.FLOAT(), nullable=True),
    sa.Column('weight_kg', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id')
    )
    op.create_index(op.f('ix_profile_anthropometry_id'), 'profile_anthropometry', ['id'], unique=False)
    op.create_table('health_documents',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('health_record_id', sa.INTEGER(), nullable=True),
    sa.Column('document_date', sa.VARCHAR(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('document_type', sa.VARCHAR(), nullable=True),
    sa.Column('file_path', sa.VARCHAR(), nullable=True),
    sa.Column('source', sa.VARCHAR(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['health_record_id'], ['health_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_documents_id'), 'health_documents', ['id'], unique=False)
    op.create_table('health_records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('person_id', sa.INTEGER(), nullable=True),
    sa.Column('summary', sa.TEXT(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id')
    )
    op.create_index(op.f('ix_health_records_id'), 'health_records', ['id'], unique=False)
    op.drop_index(op.f('ix_system_logs_id'), table_name='system_logs')
    op.drop_table('system_logs')
    # ### end Alembic commands ###